import type { Equipment, EquipmentStatus, FdcParameter, ProcessType, AnomalyScenario } from './types';
import { PROCESS_LABELS } from './constants';

// ─────────────────────────────────────────────────────────────────────────────
// Equipment Registry — SEMI E10 compliant naming, real vendor models
// ─────────────────────────────────────────────────────────────────────────────
const EQUIPMENT_REGISTRY: Equipment[] = [
  // Etch — LAM Research
  {
    equipmentId: 'ETCH-001',
    name: 'Kiyo45 #1',
    model: 'LAM 2300 Kiyo45',
    vendor: 'LAM Research',
    line: 'FAB-A',
    process: 'etch',
    status: 'RUN',
    chamberCount: 4,
    lastPmDate: '2024-03-15',
    waferCount: 2840,
  },
  {
    equipmentId: 'ETCH-002',
    name: 'Kiyo45 #2',
    model: 'LAM 2300 Kiyo45',
    vendor: 'LAM Research',
    line: 'FAB-A',
    process: 'etch',
    status: 'RUN',
    chamberCount: 4,
    lastPmDate: '2024-03-22',
    waferCount: 1950,
  },
  {
    equipmentId: 'ETCH-003',
    name: 'Versys #1',
    model: 'LAM Versys Star',
    vendor: 'LAM Research',
    line: 'FAB-B',
    process: 'etch',
    status: 'PM',
    chamberCount: 2,
    lastPmDate: '2024-04-10',
    waferCount: 3200,
  },
  // CVD — Applied Materials
  {
    equipmentId: 'CVD-001',
    name: 'Producer #1',
    model: 'AMAT Producer SE',
    vendor: 'Applied Materials',
    line: 'FAB-A',
    process: 'cvd',
    status: 'RUN',
    chamberCount: 2,
    lastPmDate: '2024-03-28',
    waferCount: 4120,
  },
  {
    equipmentId: 'CVD-002',
    name: 'Producer #2',
    model: 'AMAT Producer GT',
    vendor: 'Applied Materials',
    line: 'FAB-A',
    process: 'cvd',
    status: 'IDLE',
    chamberCount: 2,
    lastPmDate: '2024-04-02',
    waferCount: 680,
  },
  // Litho — ASML
  {
    equipmentId: 'LITHO-001',
    name: 'NXE:3600 #1',
    model: 'ASML TWINSCAN NXE:3600',
    vendor: 'ASML',
    line: 'FAB-A',
    process: 'litho',
    status: 'RUN',
    chamberCount: 1,
    lastPmDate: '2024-04-05',
    waferCount: 920,
  },
  {
    equipmentId: 'LITHO-002',
    name: 'NXT:2050i #1',
    model: 'ASML TWINSCAN NXT:2050i',
    vendor: 'ASML',
    line: 'FAB-B',
    process: 'litho',
    status: 'RUN',
    chamberCount: 1,
    lastPmDate: '2024-03-30',
    waferCount: 1560,
  },
  // CMP — Applied Materials
  {
    equipmentId: 'CMP-001',
    name: 'Reflexion LK #1',
    model: 'AMAT Reflexion LK',
    vendor: 'Applied Materials',
    line: 'FAB-A',
    process: 'cmp',
    status: 'RUN',
    chamberCount: 3,
    lastPmDate: '2024-04-01',
    waferCount: 3540,
  },
  {
    equipmentId: 'CMP-002',
    name: 'Reflexion LK #2',
    model: 'AMAT Reflexion LK',
    vendor: 'Applied Materials',
    line: 'FAB-B',
    process: 'cmp',
    status: 'DOWN',
    chamberCount: 3,
    lastPmDate: '2024-03-18',
    waferCount: 5100,
  },
  // PVD — Applied Materials
  {
    equipmentId: 'PVD-001',
    name: 'Endura #1',
    model: 'AMAT Endura Clover',
    vendor: 'Applied Materials',
    line: 'FAB-A',
    process: 'pvd',
    status: 'RUN',
    chamberCount: 5,
    lastPmDate: '2024-04-08',
    waferCount: 1230,
  },
  {
    equipmentId: 'PVD-002',
    name: 'Endura #2',
    model: 'AMAT Endura Clover',
    vendor: 'Applied Materials',
    line: 'FAB-B',
    process: 'pvd',
    status: 'ENGINEERING',
    chamberCount: 5,
    lastPmDate: '2024-03-25',
    waferCount: 2870,
  },
  // Diffusion — Tokyo Electron
  {
    equipmentId: 'DIFF-001',
    name: 'Alpha-303i #1',
    model: 'TEL Alpha-303i',
    vendor: 'Tokyo Electron',
    line: 'FAB-A',
    process: 'diffusion',
    status: 'RUN',
    chamberCount: 1,
    lastPmDate: '2024-04-03',
    waferCount: 890,
  },
  {
    equipmentId: 'DIFF-002',
    name: 'Alpha-303i #2',
    model: 'TEL Alpha-303i',
    vendor: 'Tokyo Electron',
    line: 'FAB-B',
    process: 'diffusion',
    status: 'RUN',
    chamberCount: 1,
    lastPmDate: '2024-03-20',
    waferCount: 2140,
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// Anomaly Scenarios (SEMI E164 referenced failure modes)
// ─────────────────────────────────────────────────────────────────────────────
const ANOMALY_SCENARIOS: AnomalyScenario[] = [
  {
    id: 'SCN-ETCH-001',
    process: 'etch',
    description: '챔버 압력 드리프트로 식각율 불균일 발생',
    affectedParameters: ['chamber_pressure', 'etch_rate', 'etch_uniformity', 'dc_bias'],
    rootCause:
      '쓰로틀 밸브 교정 오프셋 — 압력 제어 루프 피드백 오류로 식각율 8% 증가 및 CD 규격 이탈',
    semiReference: 'SEMI E164-0218 §5.3 Drift Detection',
  },
  {
    id: 'SCN-ETCH-002',
    process: 'etch',
    description: '소스 파워 진동으로 플라즈마 불안정 발생',
    affectedParameters: ['source_power', 'bias_power', 'etch_rate', 'selectivity'],
    rootCause:
      'RF 매칭 네트워크 부품 열화 — 임피던스 불일치로 120Hz 파워 진동, 반사 파워 >5% 시 플라즈마 미소 소멸 발생',
    semiReference: 'SEMI E164-0218 §6.1 Oscillation Pattern',
  },
  {
    id: 'SCN-CVD-001',
    process: 'cvd',
    description: 'TEOS 유량 변화로 박막 두께 불균일 발생',
    affectedParameters: ['teos_flow', 'dep_rate', 'thickness_uniformity', 'refractive_index'],
    rootCause:
      'TEOS 공급 라인 MFC 교정 드리프트 — 설정값 대비 +12% 유량 편차로 증착율 증가 및 웨이퍼 내 균일도 1.2%에서 3.8%(1σ)로 악화',
    semiReference: 'SEMI E164-0218 §5.4 Step-Change Detection',
  },
  {
    id: 'SCN-LITHO-001',
    process: 'litho',
    description: '웨이퍼 스테이지 열 드리프트로 오버레이 오차 이탈',
    affectedParameters: ['wafer_stage_temp', 'overlay_x', 'overlay_y', 'leveling_error'],
    rootCause:
      '웨이퍼 스테이지 냉각 회로 부분 막힘 — 0.15°C 열 구배로 X축 2.1nm 오버레이 오프셋, IRDS 2024 5nm 노드 예산 ±1.5nm 초과',
    semiReference: 'SEMI E164-0218 §5.5 Correlation Analysis',
  },
  {
    id: 'SCN-CMP-001',
    process: 'cmp',
    description: '패드 글레이징으로 제거율 저하 및 웨이퍼 내 불균일 발생',
    affectedParameters: ['removal_rate', 'within_wafer_nu', 'pad_temperature', 'pad_life'],
    rootCause:
      '컨디셔너 디스크 마모(수명 >85%) — 패드 표면 글레이징으로 슬러리 보유력 저하, Cu 제거율 18% 감소 및 WIWNU 3.2%에서 6.7%(범위/평균)로 악화',
    semiReference: 'SEMI E164-0218 §5.3 Trend/Drift',
  },
  {
    id: 'SCN-DIFF-001',
    process: 'diffusion',
    description: 'Zone 온도 불균일로 산화막 두께 구배 발생',
    affectedParameters: ['zone2_temp', 'zone3_temp', 'oxide_thickness', 'uniformity'],
    rootCause:
      'Zone 3 히팅 엘리먼트 부분 고장 — Zone 2와 Zone 3 간 4.2°C 온도 편차로 300mm 웨이퍼 전체 1.8Å 산화막 두께 구배, ±0.5Å 균일도 규격 초과',
    semiReference: 'SEMI E164-0218 §5.3 Gradient Detection',
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// FDC Parameter definitions by process
// Values based on 5nm FinFET node published data (IRDS 2024, IEEE IEDM proceedings)
// ─────────────────────────────────────────────────────────────────────────────

function getEtchParameters(scenario?: string): FdcParameter[] {
  const params: FdcParameter[] = [
    {
      process: 'etch',
      processLabel: PROCESS_LABELS['etch'],
      parameter: 'chamber_temp',
      description: 'Chamber wall temperature — controls etch byproduct condensation and wall chemistry',
      value: 60.2,
      unit: '°C',
      spec: '60 ± 5°C',
      ucl: 67.0,
      lcl: 53.0,
      target: 60.0,
      status: 'NORMAL',
      equipmentId: 'ETCH-001',
      semiStandard: 'SEMI E164',
    },
    {
      process: 'etch',
      processLabel: PROCESS_LABELS['etch'],
      parameter: 'chamber_pressure',
      description: 'Process chamber pressure — critical for plasma density and mean free path in HAR etch',
      value: 30.5,
      unit: 'mTorr',
      spec: '30 ± 3 mTorr',
      ucl: 33.5,
      lcl: 26.5,
      target: 30.0,
      status: 'NORMAL',
      equipmentId: 'ETCH-001',
      semiStandard: 'SEMI E164',
    },
    {
      process: 'etch',
      processLabel: PROCESS_LABELS['etch'],
      parameter: 'source_power',
      description: 'ICP source power — controls plasma density and ion flux for high-AR contact etch',
      value: 1520,
      unit: 'W',
      spec: '1500 ± 75 W',
      ucl: 1575,
      lcl: 1425,
      target: 1500,
      status: 'NORMAL',
      equipmentId: 'ETCH-001',
      semiStandard: 'SEMI E164',
    },
    {
      process: 'etch',
      processLabel: PROCESS_LABELS['etch'],
      parameter: 'bias_power',
      description: 'RF bias power — controls ion energy and directionality for anisotropic etch profile',
      value: 298,
      unit: 'W',
      spec: '300 ± 15 W',
      ucl: 315,
      lcl: 285,
      target: 300,
      status: 'NORMAL',
      equipmentId: 'ETCH-001',
      semiStandard: 'SEMI E164',
    },
    {
      process: 'etch',
      processLabel: PROCESS_LABELS['etch'],
      parameter: 'gas_flow_c4f8',
      description: 'C4F8 fluorocarbon gas flow — primary etchant for SiO2 HAR structure in 5nm node BEOL',
      value: 20.3,
      unit: 'sccm',
      spec: '20 ± 1 sccm',
      ucl: 21.5,
      lcl: 18.5,
      target: 20.0,
      status: 'NORMAL',
      equipmentId: 'ETCH-001',
      semiStandard: 'SEMI E164',
    },
    {
      process: 'etch',
      processLabel: PROCESS_LABELS['etch'],
      parameter: 'gas_flow_o2',
      description: 'O2 gas flow — controls polymer passivation vs. etch rate balance, critical for sidewall profile',
      value: 4.8,
      unit: 'sccm',
      spec: '5 ± 0.5 sccm',
      ucl: 5.8,
      lcl: 4.2,
      target: 5.0,
      status: 'WARNING',
      equipmentId: 'ETCH-001',
      semiStandard: 'SEMI E164',
    },
    {
      process: 'etch',
      processLabel: PROCESS_LABELS['etch'],
      parameter: 'gas_flow_ar',
      description: 'Ar gas flow — inert diluent for plasma stability and ion bombardment energy distribution',
      value: 400.1,
      unit: 'sccm',
      spec: '400 ± 20 sccm',
      ucl: 425,
      lcl: 375,
      target: 400,
      status: 'NORMAL',
      equipmentId: 'ETCH-001',
      semiStandard: 'SEMI E164',
    },
    {
      process: 'etch',
      processLabel: PROCESS_LABELS['etch'],
      parameter: 'gas_flow_n2',
      description: 'N2 gas flow — sidewall passivation agent for 5nm node FinFET gate etch',
      value: 10.1,
      unit: 'sccm',
      spec: '10 ± 1 sccm',
      ucl: 11.5,
      lcl: 8.5,
      target: 10.0,
      status: 'NORMAL',
      equipmentId: 'ETCH-001',
      semiStandard: 'SEMI E164',
    },
    {
      process: 'etch',
      processLabel: PROCESS_LABELS['etch'],
      parameter: 'etch_rate',
      description: 'SiO2 etch rate measured by OES endpoint — target for 10:1 AR contact etch at 5nm node',
      value: 485,
      unit: 'Å/min',
      spec: '500 ± 25 Å/min',
      ucl: 530,
      lcl: 470,
      target: 500,
      status: 'NORMAL',
      equipmentId: 'ETCH-001',
      semiStandard: 'SEMI E164',
    },
    {
      process: 'etch',
      processLabel: PROCESS_LABELS['etch'],
      parameter: 'etch_uniformity',
      description: 'Within-wafer etch rate uniformity (1σ/mean) — IRDS 2024 target <2% for 5nm node',
      value: 1.8,
      unit: '%',
      spec: '< 2.0%',
      ucl: 2.5,
      lcl: 0.0,
      target: 1.2,
      status: 'NORMAL',
      equipmentId: 'ETCH-001',
      semiStandard: 'SEMI E164',
    },
    {
      process: 'etch',
      processLabel: PROCESS_LABELS['etch'],
      parameter: 'selectivity',
      description: 'SiO2:Si3N4 etch selectivity ratio — must be >15:1 for 5nm node SAC etch',
      value: 17.2,
      unit: ':1',
      spec: '> 15.0:1',
      ucl: 25.0,
      lcl: 14.0,
      target: 18.0,
      status: 'NORMAL',
      equipmentId: 'ETCH-001',
      semiStandard: 'SEMI E164',
    },
    {
      process: 'etch',
      processLabel: PROCESS_LABELS['etch'],
      parameter: 'endpoint_time',
      description: 'OES optical endpoint detection time — indicates etch depth and process stability',
      value: 145,
      unit: 's',
      spec: '150 ± 20 s',
      ucl: 175,
      lcl: 125,
      target: 150,
      status: 'NORMAL',
      equipmentId: 'ETCH-001',
      semiStandard: 'SEMI E164',
    },
    {
      process: 'etch',
      processLabel: PROCESS_LABELS['etch'],
      parameter: 'dc_bias',
      description: 'Self-induced DC bias voltage — direct indicator of ion bombardment energy at wafer surface',
      value: -185,
      unit: 'V',
      spec: '-180 ± 20 V',
      ucl: -155,
      lcl: -205,
      target: -180,
      status: 'NORMAL',
      equipmentId: 'ETCH-001',
      semiStandard: 'SEMI E164',
    },
  ];

  if (scenario === 'SCN-ETCH-001') {
    // Pressure drift scenario
    return params.map((p) => {
      if (p.parameter === 'chamber_pressure') return { ...p, value: 34.8, status: 'OOS' };
      if (p.parameter === 'etch_rate') return { ...p, value: 541, status: 'OOS' };
      if (p.parameter === 'etch_uniformity') return { ...p, value: 3.2, status: 'OOS' };
      if (p.parameter === 'dc_bias') return { ...p, value: -165, status: 'WARNING' };
      return p;
    });
  }
  if (scenario === 'SCN-ETCH-002') {
    // RF oscillation scenario
    return params.map((p) => {
      if (p.parameter === 'source_power') return { ...p, value: 1648, status: 'OOS' };
      if (p.parameter === 'bias_power') return { ...p, value: 326, status: 'WARNING' };
      if (p.parameter === 'etch_rate') return { ...p, value: 556, status: 'OOS' };
      if (p.parameter === 'selectivity') return { ...p, value: 11.4, status: 'OOS' };
      return p;
    });
  }
  return params;
}

function getCvdParameters(scenario?: string): FdcParameter[] {
  const params: FdcParameter[] = [
    {
      process: 'cvd',
      processLabel: PROCESS_LABELS['cvd'],
      parameter: 'susceptor_temp',
      description: 'Susceptor/heater temperature — primary deposition rate control for TEOS-based PECVD',
      value: 400.3,
      unit: '°C',
      spec: '400 ± 3°C',
      ucl: 404.0,
      lcl: 396.0,
      target: 400.0,
      status: 'NORMAL',
      equipmentId: 'CVD-001',
      semiStandard: 'SEMI E164',
    },
    {
      process: 'cvd',
      processLabel: PROCESS_LABELS['cvd'],
      parameter: 'chamber_pressure',
      description: 'Process chamber pressure for TEOS-PECVD — controls mean free path and deposition conformality',
      value: 8.1,
      unit: 'Torr',
      spec: '8.0 ± 0.5 Torr',
      ucl: 8.8,
      lcl: 7.2,
      target: 8.0,
      status: 'NORMAL',
      equipmentId: 'CVD-001',
      semiStandard: 'SEMI E164',
    },
    {
      process: 'cvd',
      processLabel: PROCESS_LABELS['cvd'],
      parameter: 'teos_flow',
      description: 'Tetraethylorthosilicate (TEOS) liquid precursor flow rate for SiO2 PMD/ILD deposition',
      value: 1000,
      unit: 'mgm',
      spec: '1000 ± 50 mgm',
      ucl: 1060,
      lcl: 940,
      target: 1000,
      status: 'NORMAL',
      equipmentId: 'CVD-001',
      semiStandard: 'SEMI E164',
    },
    {
      process: 'cvd',
      processLabel: PROCESS_LABELS['cvd'],
      parameter: 'o2_flow',
      description: 'O2 oxidant flow for TEOS-PECVD — stoichiometry control for SiO2 film quality',
      value: 9200,
      unit: 'sccm',
      spec: '9000 ± 300 sccm',
      ucl: 9500,
      lcl: 8500,
      target: 9000,
      status: 'NORMAL',
      equipmentId: 'CVD-001',
      semiStandard: 'SEMI E164',
    },
    {
      process: 'cvd',
      processLabel: PROCESS_LABELS['cvd'],
      parameter: 'sih4_flow',
      description: 'SiH4 silane flow for Si-rich nitride or oxide cap layers in 5nm BEOL stack',
      value: 180,
      unit: 'sccm',
      spec: '180 ± 10 sccm',
      ucl: 195,
      lcl: 165,
      target: 180,
      status: 'NORMAL',
      equipmentId: 'CVD-001',
      semiStandard: 'SEMI E164',
    },
    {
      process: 'cvd',
      processLabel: PROCESS_LABELS['cvd'],
      parameter: 'dep_rate',
      description: 'Film deposition rate — product of temperature, pressure and precursor flow interaction',
      value: 1850,
      unit: 'Å/min',
      spec: '1800 ± 100 Å/min',
      ucl: 1960,
      lcl: 1640,
      target: 1800,
      status: 'NORMAL',
      equipmentId: 'CVD-001',
      semiStandard: 'SEMI E164',
    },
    {
      process: 'cvd',
      processLabel: PROCESS_LABELS['cvd'],
      parameter: 'thickness_uniformity',
      description: 'Within-wafer film thickness non-uniformity (1σ) — IRDS 2024 target <1.5% for ILD',
      value: 1.2,
      unit: '%',
      spec: '< 1.5%',
      ucl: 1.8,
      lcl: 0.0,
      target: 0.8,
      status: 'NORMAL',
      equipmentId: 'CVD-001',
      semiStandard: 'SEMI E164',
    },
    {
      process: 'cvd',
      processLabel: PROCESS_LABELS['cvd'],
      parameter: 'refractive_index',
      description: 'Film refractive index at 632nm — indicator of film stoichiometry (SiO2 target: 1.46)',
      value: 1.461,
      unit: 'n',
      spec: '1.46 ± 0.01',
      ucl: 1.472,
      lcl: 1.448,
      target: 1.460,
      status: 'NORMAL',
      equipmentId: 'CVD-001',
      semiStandard: 'SEMI E164',
    },
    {
      process: 'cvd',
      processLabel: PROCESS_LABELS['cvd'],
      parameter: 'film_stress',
      description: 'Intrinsic film stress — compressive stress control for warpage in advanced node BEOL',
      value: -285,
      unit: 'MPa',
      spec: '-300 ± 50 MPa',
      ucl: -230,
      lcl: -370,
      target: -300,
      status: 'NORMAL',
      equipmentId: 'CVD-001',
      semiStandard: 'SEMI E164',
    },
    {
      process: 'cvd',
      processLabel: PROCESS_LABELS['cvd'],
      parameter: 'particle_count',
      description: 'In-situ particle count (>0.09μm) — ITRS defect density target for 5nm node',
      value: 3,
      unit: 'particles/wafer',
      spec: '< 5 particles/wafer',
      ucl: 7,
      lcl: 0,
      target: 0,
      status: 'NORMAL',
      equipmentId: 'CVD-001',
      semiStandard: 'SEMI E164',
    },
  ];

  if (scenario === 'SCN-CVD-001') {
    return params.map((p) => {
      if (p.parameter === 'teos_flow') return { ...p, value: 1122, status: 'OOS' };
      if (p.parameter === 'dep_rate') return { ...p, value: 2016, status: 'OOS' };
      if (p.parameter === 'thickness_uniformity') return { ...p, value: 3.8, status: 'OOS' };
      if (p.parameter === 'refractive_index') return { ...p, value: 1.451, status: 'WARNING' };
      return p;
    });
  }
  return params;
}

function getLithoParameters(scenario?: string): FdcParameter[] {
  const params: FdcParameter[] = [
    {
      process: 'litho',
      processLabel: PROCESS_LABELS['litho'],
      parameter: 'wafer_stage_temp',
      description: 'Wafer stage temperature — thermal stability critical for overlay budget in EUV lithography',
      value: 22.01,
      unit: '°C',
      spec: '22.0 ± 0.05°C',
      ucl: 22.06,
      lcl: 21.94,
      target: 22.0,
      status: 'NORMAL',
      equipmentId: 'LITHO-001',
      semiStandard: 'SEMI E164',
    },
    {
      process: 'litho',
      processLabel: PROCESS_LABELS['litho'],
      parameter: 'exposure_dose',
      description: 'EUV exposure dose — controls CD through dose-to-size relationship at 13.5nm wavelength',
      value: 30.2,
      unit: 'mJ/cm²',
      spec: '30 ± 1 mJ/cm²',
      ucl: 31.5,
      lcl: 28.5,
      target: 30.0,
      status: 'NORMAL',
      equipmentId: 'LITHO-001',
      semiStandard: 'SEMI E164',
    },
    {
      process: 'litho',
      processLabel: PROCESS_LABELS['litho'],
      parameter: 'focus_offset',
      description: 'Aerial image focus offset from best focus — DOF budget for 5nm node is ±60nm',
      value: 8,
      unit: 'nm',
      spec: '0 ± 20 nm',
      ucl: 22,
      lcl: -22,
      target: 0,
      status: 'NORMAL',
      equipmentId: 'LITHO-001',
      semiStandard: 'SEMI E164',
    },
    {
      process: 'litho',
      processLabel: PROCESS_LABELS['litho'],
      parameter: 'resist_thickness',
      description: 'EUV photoresist thickness — ultra-thin resist required for 5nm node CD budget',
      value: 38.2,
      unit: 'nm',
      spec: '38 ± 2 nm',
      ucl: 40.5,
      lcl: 35.5,
      target: 38.0,
      status: 'NORMAL',
      equipmentId: 'LITHO-001',
      semiStandard: 'SEMI E164',
    },
    {
      process: 'litho',
      processLabel: PROCESS_LABELS['litho'],
      parameter: 'develop_time',
      description: 'TMAH developer immersion time — controls resist dissolution and CD bias in patterning',
      value: 30.5,
      unit: 's',
      spec: '30 ± 2 s',
      ucl: 33.0,
      lcl: 27.0,
      target: 30.0,
      status: 'NORMAL',
      equipmentId: 'LITHO-001',
      semiStandard: 'SEMI E164',
    },
    {
      process: 'litho',
      processLabel: PROCESS_LABELS['litho'],
      parameter: 'overlay_x',
      description: 'Overlay registration error in X-axis — IRDS 2024 budget ±1.5nm (3σ) for 5nm node',
      value: 0.8,
      unit: 'nm',
      spec: '0 ± 1.5 nm',
      ucl: 1.8,
      lcl: -1.8,
      target: 0.0,
      status: 'NORMAL',
      equipmentId: 'LITHO-001',
      semiStandard: 'SEMI E164',
    },
    {
      process: 'litho',
      processLabel: PROCESS_LABELS['litho'],
      parameter: 'overlay_y',
      description: 'Overlay registration error in Y-axis — IRDS 2024 budget ±1.5nm (3σ) for 5nm node',
      value: 0.6,
      unit: 'nm',
      spec: '0 ± 1.5 nm',
      ucl: 1.8,
      lcl: -1.8,
      target: 0.0,
      status: 'NORMAL',
      equipmentId: 'LITHO-001',
      semiStandard: 'SEMI E164',
    },
    {
      process: 'litho',
      processLabel: PROCESS_LABELS['litho'],
      parameter: 'cd_uniformity',
      description: 'Critical dimension uniformity (3σ) — gate CD budget for 5nm FinFET: ±0.5nm',
      value: 0.42,
      unit: 'nm',
      spec: '< 0.5 nm',
      ucl: 0.6,
      lcl: 0.0,
      target: 0.3,
      status: 'NORMAL',
      equipmentId: 'LITHO-001',
      semiStandard: 'SEMI E164',
    },
    {
      process: 'litho',
      processLabel: PROCESS_LABELS['litho'],
      parameter: 'dose_uniformity',
      description: 'Across-wafer dose uniformity (3σ/mean) — EUV source power stability requirement',
      value: 0.18,
      unit: '%',
      spec: '< 0.25%',
      ucl: 0.30,
      lcl: 0.0,
      target: 0.15,
      status: 'NORMAL',
      equipmentId: 'LITHO-001',
      semiStandard: 'SEMI E164',
    },
    {
      process: 'litho',
      processLabel: PROCESS_LABELS['litho'],
      parameter: 'leveling_error',
      description: 'Wafer leveling (focus map) residual error — flatness correction limit in EUV scanner',
      value: 5.2,
      unit: 'nm',
      spec: '< 8 nm',
      ucl: 10,
      lcl: 0,
      target: 0,
      status: 'NORMAL',
      equipmentId: 'LITHO-001',
      semiStandard: 'SEMI E164',
    },
  ];

  if (scenario === 'SCN-LITHO-001') {
    return params.map((p) => {
      if (p.parameter === 'wafer_stage_temp') return { ...p, value: 22.18, status: 'OOS' };
      if (p.parameter === 'overlay_x') return { ...p, value: 2.1, status: 'OOS' };
      if (p.parameter === 'overlay_y') return { ...p, value: 1.7, status: 'WARNING' };
      if (p.parameter === 'leveling_error') return { ...p, value: 11.4, status: 'OOS' };
      return p;
    });
  }
  return params;
}

function getCmpParameters(scenario?: string): FdcParameter[] {
  const params: FdcParameter[] = [
    {
      process: 'cmp',
      processLabel: PROCESS_LABELS['cmp'],
      parameter: 'platen_speed',
      description: 'Polishing platen rotation speed — primary variable in Preston equation for removal rate',
      value: 93,
      unit: 'rpm',
      spec: '93 ± 5 rpm',
      ucl: 100,
      lcl: 86,
      target: 93,
      status: 'NORMAL',
      equipmentId: 'CMP-001',
      semiStandard: 'SEMI E164',
    },
    {
      process: 'cmp',
      processLabel: PROCESS_LABELS['cmp'],
      parameter: 'carrier_speed',
      description: 'Wafer carrier head rotation speed — affects relative velocity for Preston equation',
      value: 87,
      unit: 'rpm',
      spec: '87 ± 5 rpm',
      ucl: 94,
      lcl: 80,
      target: 87,
      status: 'NORMAL',
      equipmentId: 'CMP-001',
      semiStandard: 'SEMI E164',
    },
    {
      process: 'cmp',
      processLabel: PROCESS_LABELS['cmp'],
      parameter: 'down_force',
      description: 'Carrier head down pressure — controls Preston constant and removal rate in Cu CMP',
      value: 2.1,
      unit: 'psi',
      spec: '2.1 ± 0.2 psi',
      ucl: 2.4,
      lcl: 1.8,
      target: 2.1,
      status: 'NORMAL',
      equipmentId: 'CMP-001',
      semiStandard: 'SEMI E164',
    },
    {
      process: 'cmp',
      processLabel: PROCESS_LABELS['cmp'],
      parameter: 'slurry_flow_rate',
      description: 'Abrasive slurry delivery rate — affects lubrication regime and particle refresh at pad',
      value: 200,
      unit: 'mL/min',
      spec: '200 ± 20 mL/min',
      ucl: 225,
      lcl: 175,
      target: 200,
      status: 'NORMAL',
      equipmentId: 'CMP-001',
      semiStandard: 'SEMI E164',
    },
    {
      process: 'cmp',
      processLabel: PROCESS_LABELS['cmp'],
      parameter: 'slurry_temperature',
      description: 'Slurry delivery temperature — thermal control for consistent chemical mechanical removal',
      value: 22.4,
      unit: '°C',
      spec: '22 ± 1°C',
      ucl: 23.5,
      lcl: 20.5,
      target: 22.0,
      status: 'NORMAL',
      equipmentId: 'CMP-001',
      semiStandard: 'SEMI E164',
    },
    {
      process: 'cmp',
      processLabel: PROCESS_LABELS['cmp'],
      parameter: 'removal_rate',
      description: 'Cu film removal rate by in-situ ISRM — target for 70nm Cu damascene at 5nm node',
      value: 3850,
      unit: 'Å/min',
      spec: '3800 ± 200 Å/min',
      ucl: 4100,
      lcl: 3500,
      target: 3800,
      status: 'NORMAL',
      equipmentId: 'CMP-001',
      semiStandard: 'SEMI E164',
    },
    {
      process: 'cmp',
      processLabel: PROCESS_LABELS['cmp'],
      parameter: 'pad_temperature',
      description: 'Polishing pad surface temperature — friction indicator and process stability proxy',
      value: 38.2,
      unit: '°C',
      spec: '40 ± 5°C',
      ucl: 47,
      lcl: 33,
      target: 40,
      status: 'NORMAL',
      equipmentId: 'CMP-001',
      semiStandard: 'SEMI E164',
    },
    {
      process: 'cmp',
      processLabel: PROCESS_LABELS['cmp'],
      parameter: 'pad_life',
      description: 'Polishing pad utilization (% of qualified life) — glazing risk above 80%',
      value: 62,
      unit: '%',
      spec: '< 80%',
      ucl: 85,
      lcl: 0,
      target: 50,
      status: 'NORMAL',
      equipmentId: 'CMP-001',
      semiStandard: 'SEMI E164',
    },
    {
      process: 'cmp',
      processLabel: PROCESS_LABELS['cmp'],
      parameter: 'within_wafer_nu',
      description: 'Within-wafer non-uniformity (range/mean) — IRDS Cu CMP target <3% for 5nm node',
      value: 3.1,
      unit: '%',
      spec: '< 3.0%',
      ucl: 4.0,
      lcl: 0.0,
      target: 2.0,
      status: 'WARNING',
      equipmentId: 'CMP-001',
      semiStandard: 'SEMI E164',
    },
    {
      process: 'cmp',
      processLabel: PROCESS_LABELS['cmp'],
      parameter: 'post_thickness',
      description: 'Post-CMP Cu remaining thickness measured by XRF — target for dual damascene structure',
      value: 71.8,
      unit: 'nm',
      spec: '70 ± 5 nm',
      ucl: 76,
      lcl: 64,
      target: 70,
      status: 'NORMAL',
      equipmentId: 'CMP-001',
      semiStandard: 'SEMI E164',
    },
  ];

  if (scenario === 'SCN-CMP-001') {
    return params.map((p) => {
      if (p.parameter === 'removal_rate') return { ...p, value: 3116, status: 'OOS' };
      if (p.parameter === 'within_wafer_nu') return { ...p, value: 6.7, status: 'OOS' };
      if (p.parameter === 'pad_temperature') return { ...p, value: 47.8, status: 'WARNING' };
      if (p.parameter === 'pad_life') return { ...p, value: 88, status: 'OOS' };
      return p;
    });
  }
  return params;
}

function getPvdParameters(): FdcParameter[] {
  return [
    {
      process: 'pvd',
      processLabel: PROCESS_LABELS['pvd'],
      parameter: 'chamber_pressure',
      description: 'Base and process pressure during Ar sputtering — affects film microstructure and step coverage',
      value: 2.8,
      unit: 'mTorr',
      spec: '3.0 ± 0.5 mTorr',
      ucl: 3.7,
      lcl: 2.3,
      target: 3.0,
      status: 'NORMAL',
      equipmentId: 'PVD-001',
      semiStandard: 'SEMI E164',
    },
    {
      process: 'pvd',
      processLabel: PROCESS_LABELS['pvd'],
      parameter: 'dc_power',
      description: 'DC magnetron sputter power for TaN/Ta barrier and Cu seed deposition',
      value: 18200,
      unit: 'W',
      spec: '18000 ± 500 W',
      ucl: 18750,
      lcl: 17250,
      target: 18000,
      status: 'NORMAL',
      equipmentId: 'PVD-001',
      semiStandard: 'SEMI E164',
    },
    {
      process: 'pvd',
      processLabel: PROCESS_LABELS['pvd'],
      parameter: 'ar_flow',
      description: 'Argon sputter gas flow — controls ionization density and target utilization efficiency',
      value: 45.2,
      unit: 'sccm',
      spec: '45 ± 5 sccm',
      ucl: 52,
      lcl: 38,
      target: 45,
      status: 'NORMAL',
      equipmentId: 'PVD-001',
      semiStandard: 'SEMI E164',
    },
    {
      process: 'pvd',
      processLabel: PROCESS_LABELS['pvd'],
      parameter: 'substrate_temp',
      description: 'Substrate temperature during deposition — controls grain growth and resistivity in Cu seed',
      value: 248,
      unit: '°C',
      spec: '250 ± 10°C',
      ucl: 262,
      lcl: 238,
      target: 250,
      status: 'NORMAL',
      equipmentId: 'PVD-001',
      semiStandard: 'SEMI E164',
    },
    {
      process: 'pvd',
      processLabel: PROCESS_LABELS['pvd'],
      parameter: 'target_life',
      description: 'Sputter target utilization (% of qualified life) — erosion affects uniformity above 85%',
      value: 71,
      unit: '%',
      spec: '< 85%',
      ucl: 90,
      lcl: 0,
      target: 50,
      status: 'NORMAL',
      equipmentId: 'PVD-001',
      semiStandard: 'SEMI E164',
    },
    {
      process: 'pvd',
      processLabel: PROCESS_LABELS['pvd'],
      parameter: 'dep_rate',
      description: 'Thin film deposition rate for TaN barrier — control via DC power and Ar pressure',
      value: 42,
      unit: 'Å/min',
      spec: '40 ± 5 Å/min',
      ucl: 47,
      lcl: 33,
      target: 40,
      status: 'NORMAL',
      equipmentId: 'PVD-001',
      semiStandard: 'SEMI E164',
    },
    {
      process: 'pvd',
      processLabel: PROCESS_LABELS['pvd'],
      parameter: 'sheet_resistance',
      description: 'Post-deposition sheet resistance (Rs) for TaN barrier layer — target for 7nm wide trench',
      value: 148,
      unit: 'Ω/sq',
      spec: '150 ± 15 Ω/sq',
      ucl: 168,
      lcl: 132,
      target: 150,
      status: 'NORMAL',
      equipmentId: 'PVD-001',
      semiStandard: 'SEMI E164',
    },
    {
      process: 'pvd',
      processLabel: PROCESS_LABELS['pvd'],
      parameter: 'film_adhesion',
      description: 'Film adhesion strength measured by scratch test — interface quality indicator for Cu barrier',
      value: 8.4,
      unit: 'GPa',
      spec: '> 7.0 GPa',
      ucl: 12.0,
      lcl: 6.5,
      target: 9.0,
      status: 'NORMAL',
      equipmentId: 'PVD-001',
      semiStandard: 'SEMI E164',
    },
  ];
}

function getDiffusionParameters(scenario?: string): FdcParameter[] {
  const params: FdcParameter[] = [
    {
      process: 'diffusion',
      processLabel: PROCESS_LABELS['diffusion'],
      parameter: 'zone1_temp',
      description: 'Furnace zone 1 (inlet) temperature — ramping zone for wafer thermal equilibration',
      value: 799.8,
      unit: '°C',
      spec: '800 ± 2°C',
      ucl: 803,
      lcl: 797,
      target: 800,
      status: 'NORMAL',
      equipmentId: 'DIFF-001',
      semiStandard: 'SEMI E164',
    },
    {
      process: 'diffusion',
      processLabel: PROCESS_LABELS['diffusion'],
      parameter: 'zone2_temp',
      description: 'Furnace zone 2 temperature — first isothermal zone for initial oxide growth',
      value: 1000.1,
      unit: '°C',
      spec: '1000 ± 1°C',
      ucl: 1002,
      lcl: 998,
      target: 1000,
      status: 'NORMAL',
      equipmentId: 'DIFF-001',
      semiStandard: 'SEMI E164',
    },
    {
      process: 'diffusion',
      processLabel: PROCESS_LABELS['diffusion'],
      parameter: 'zone3_temp',
      description: 'Furnace zone 3 temperature — primary oxidation zone, most critical for uniformity',
      value: 999.8,
      unit: '°C',
      spec: '1000 ± 1°C',
      ucl: 1002,
      lcl: 998,
      target: 1000,
      status: 'NORMAL',
      equipmentId: 'DIFF-001',
      semiStandard: 'SEMI E164',
    },
    {
      process: 'diffusion',
      processLabel: PROCESS_LABELS['diffusion'],
      parameter: 'zone4_temp',
      description: 'Furnace zone 4 temperature — second isothermal zone for oxidation completion',
      value: 1000.3,
      unit: '°C',
      spec: '1000 ± 1°C',
      ucl: 1002,
      lcl: 998,
      target: 1000,
      status: 'NORMAL',
      equipmentId: 'DIFF-001',
      semiStandard: 'SEMI E164',
    },
    {
      process: 'diffusion',
      processLabel: PROCESS_LABELS['diffusion'],
      parameter: 'zone5_temp',
      description: 'Furnace zone 5 (outlet) temperature — cooling zone for stress-free wafer unloading',
      value: 800.2,
      unit: '°C',
      spec: '800 ± 2°C',
      ucl: 803,
      lcl: 797,
      target: 800,
      status: 'NORMAL',
      equipmentId: 'DIFF-001',
      semiStandard: 'SEMI E164',
    },
    {
      process: 'diffusion',
      processLabel: PROCESS_LABELS['diffusion'],
      parameter: 'o2_flow',
      description: 'O2 oxidant flow rate for dry/wet thermal oxidation of gate oxide (SiO2) growth',
      value: 8.0,
      unit: 'L/min',
      spec: '8.0 ± 0.2 L/min',
      ucl: 8.3,
      lcl: 7.7,
      target: 8.0,
      status: 'NORMAL',
      equipmentId: 'DIFF-001',
      semiStandard: 'SEMI E164',
    },
    {
      process: 'diffusion',
      processLabel: PROCESS_LABELS['diffusion'],
      parameter: 'n2_flow',
      description: 'N2 carrier/purge gas flow — maintains laminar flow profile and O2 partial pressure control',
      value: 15.1,
      unit: 'L/min',
      spec: '15.0 ± 0.5 L/min',
      ucl: 16.0,
      lcl: 14.0,
      target: 15.0,
      status: 'NORMAL',
      equipmentId: 'DIFF-001',
      semiStandard: 'SEMI E164',
    },
    {
      process: 'diffusion',
      processLabel: PROCESS_LABELS['diffusion'],
      parameter: 'dcl_hcl_flow',
      description: 'DCL/HCl chlorine source flow for metallic contamination gettering during gate oxidation',
      value: 0.5,
      unit: 'L/min',
      spec: '0.5 ± 0.05 L/min',
      ucl: 0.58,
      lcl: 0.42,
      target: 0.5,
      status: 'NORMAL',
      equipmentId: 'DIFF-001',
      semiStandard: 'SEMI E164',
    },
    {
      process: 'diffusion',
      processLabel: PROCESS_LABELS['diffusion'],
      parameter: 'process_time',
      description: 'Total oxidation process time — Deal-Grove model dependent on target oxide thickness',
      value: 32.5,
      unit: 'min',
      spec: '32 ± 1 min',
      ucl: 33.5,
      lcl: 30.5,
      target: 32.0,
      status: 'NORMAL',
      equipmentId: 'DIFF-001',
      semiStandard: 'SEMI E164',
    },
    {
      process: 'diffusion',
      processLabel: PROCESS_LABELS['diffusion'],
      parameter: 'oxide_thickness',
      description: 'Gate oxide (SiO2) thickness measured by ellipsometry — EOT target for 5nm FinFET: 1.2nm',
      value: 12.1,
      unit: 'Å',
      spec: '12 ± 0.5 Å',
      ucl: 12.8,
      lcl: 11.2,
      target: 12.0,
      status: 'NORMAL',
      equipmentId: 'DIFF-001',
      semiStandard: 'SEMI E164',
    },
    {
      process: 'diffusion',
      processLabel: PROCESS_LABELS['diffusion'],
      parameter: 'uniformity',
      description: 'Oxide thickness uniformity across 300mm wafer (1σ) — target <0.5Å for gate dielectric',
      value: 0.38,
      unit: 'Å',
      spec: '< 0.5 Å',
      ucl: 0.6,
      lcl: 0.0,
      target: 0.25,
      status: 'NORMAL',
      equipmentId: 'DIFF-001',
      semiStandard: 'SEMI E164',
    },
  ];

  if (scenario === 'SCN-DIFF-001') {
    return params.map((p) => {
      if (p.parameter === 'zone3_temp') return { ...p, value: 995.8, status: 'OOS' };
      if (p.parameter === 'zone2_temp') return { ...p, value: 1000.1, status: 'NORMAL' };
      if (p.parameter === 'oxide_thickness') return { ...p, value: 13.8, status: 'OOS' };
      if (p.parameter === 'uniformity') return { ...p, value: 0.72, status: 'OOS' };
      return p;
    });
  }
  return params;
}

// ─────────────────────────────────────────────────────────────────────────────
// Public API
// ─────────────────────────────────────────────────────────────────────────────

export function getFdcData(process?: ProcessType, scenario?: string): FdcParameter[] {
  const all: FdcParameter[] = [
    ...getEtchParameters(scenario),
    ...getCvdParameters(scenario),
    ...getLithoParameters(scenario),
    ...getCmpParameters(scenario),
    ...getPvdParameters(),
    ...getDiffusionParameters(scenario),
  ];
  if (!process) return all;
  return all.filter((p) => p.process === process);
}

export function getAnomalyScenarios(): AnomalyScenario[] {
  return ANOMALY_SCENARIOS;
}

export function getEquipmentList(): Equipment[] {
  return EQUIPMENT_REGISTRY;
}

export function getEquipmentByProcess(process: ProcessType): Equipment[] {
  return EQUIPMENT_REGISTRY.filter((e) => e.process === process);
}

export function getKpiData() {
  const eq = EQUIPMENT_REGISTRY;
  const byStatus = eq.reduce(
    (acc, e) => {
      acc[e.status] = (acc[e.status] || 0) + 1;
      return acc;
    },
    {} as Record<EquipmentStatus, number>,
  );

  const allParams = getFdcData();
  const oosCount = allParams.filter((p) => p.status === 'OOS').length;

  return {
    totalEquipment: eq.length,
    activeAlarms: 7,
    oosParameters: oosCount,
    avgCpk: 1.42,
    oee: 82.4,
    equipmentByStatus: {
      RUN: byStatus['RUN'] || 0,
      IDLE: byStatus['IDLE'] || 0,
      DOWN: byStatus['DOWN'] || 0,
      PM: byStatus['PM'] || 0,
      ENGINEERING: byStatus['ENGINEERING'] || 0,
    },
    alarmsBySeverity: {
      CRITICAL: 2,
      WARNING: 4,
      INFO: 1,
    },
  };
}
